/**
 * Pactwork Storybook Addon Types
 *
 * Type definitions for story parameters and addon state.
 */

import type { HttpHandler } from 'msw';
import type {
  HandlerMetaMap,
  ScenarioMap,
  LatencyOptions,
  NetworkErrorOptions,
} from 'pactwork/runtime';

/**
 * Pactwork parameters for story configuration.
 *
 * @example
 * ```typescript
 * export const Loading: Story = {
 *   parameters: {
 *     pactwork: {
 *       scenario: 'getUser.loading',
 *       latency: 2000
 *     }
 *   }
 * }
 * ```
 */
export interface PactworkParameters {
  /**
   * Scenario to apply. Format: 'operationId.scenarioName' or just 'scenarioName'.
   * When just scenarioName is provided, it applies to all matching operations.
   */
  scenario?: string;

  /**
   * Multiple scenarios to apply simultaneously.
   * Format: ['operationId.scenarioName', 'anotherOp.otherScenario']
   */
  scenarios?: string[];

  /**
   * Latency to add to all handlers in milliseconds.
   * Can be a number for fixed delay or an object with min/max for random range.
   */
  latency?: number | LatencyOptions;

  /**
   * Network error to simulate.
   * Can be 'timeout', 'abort', 'network-error', or a full NetworkErrorOptions object.
   */
  networkError?: NetworkErrorOptions['type'] | NetworkErrorOptions;

  /**
   * Specific operation IDs to apply latency/network errors to.
   * If not specified, applies to all handlers.
   */
  operations?: string[];

  /**
   * Whether to disable pactwork transformations for this story.
   */
  disabled?: boolean;
}

/**
 * Global pactwork configuration provided via preview.ts or config files.
 */
export interface PactworkGlobalConfig {
  /**
   * MSW handlers generated by pactwork.
   */
  handlers: HttpHandler[];

  /**
   * Handler metadata map for O(1) lookups.
   */
  handlerMeta: HandlerMetaMap;

  /**
   * Available scenarios organized by operationId.
   */
  scenarios: Record<string, ScenarioMap>;

  /**
   * Default latency to apply to all handlers.
   */
  defaultLatency?: number | LatencyOptions;

  /**
   * Whether to log handler transformations to console.
   */
  debug?: boolean;
}

/**
 * State managed by the addon panel.
 */
export interface PactworkPanelState {
  /** Currently selected scenario (operationId.scenarioName) */
  selectedScenario: string | null;
  /** Current latency in milliseconds */
  latency: number;
  /** Current network error type or null */
  networkError: NetworkErrorOptions['type'] | null;
  /** Whether transformations are enabled */
  enabled: boolean;
}

/**
 * Message payload for scenario change events.
 */
export interface ScenarioChangePayload {
  /** The scenario identifier (operationId.scenarioName) */
  scenario: string | null;
  /** Optional operation ID if scenario is just scenarioName */
  operationId?: string;
}

/**
 * Message payload for latency change events.
 */
export interface LatencyChangePayload {
  /** Latency in milliseconds */
  latency: number;
  /** Optional specific operations to apply to */
  operations?: string[];
}

/**
 * Message payload for network change events.
 */
export interface NetworkChangePayload {
  /** Network error type or null to disable */
  type: NetworkErrorOptions['type'] | null;
  /** Optional delay before error */
  delay?: number;
  /** Optional specific operations to apply to */
  operations?: string[];
}

/**
 * Handler info displayed in the panel.
 */
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';

export interface HandlerInfo {
  operationId: string;
  method: HttpMethod;
  path: string;
  availableScenarios: string[];
}

// Note: Type augmentation for Parameters should be done in consuming projects
// via their own .d.ts files if needed for autocomplete
