import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { createHash } from 'node:crypto'
import fs from 'fs-extra'
import path from 'path'
import chalk from 'chalk'
import { parseSpec, parseSpecFast } from '../parser/index.js'
import type { GeneratorOptions, GeneratorResult } from './types.js'

export type { GeneratorOptions, GeneratorResult, HandlerInfo } from './types.js'

const execFileAsync = promisify(execFile)

/**
 * Generate MSW handlers from an OpenAPI specification
 */
export async function generateHandlers(options: GeneratorOptions): Promise<GeneratorResult> {
  const { specPath, outputDir } = options

  // Ensure output directory exists
  await fs.ensureDir(outputDir)

  // Calculate spec hash for tracking
  const specContent = await fs.readFile(specPath, 'utf-8')
  const specHash = createHash('sha256').update(specContent).digest('hex').slice(0, 12)

  // Parse spec to get endpoint info
  // Use fast parsing (no validation) if skipValidation is true
  const spec = options.skipValidation
    ? await parseSpecFast(specPath)
    : await parseSpec(specPath)

  // Build arguments for msw-auto-mock
  const args = buildArgs(options)

  try {
    // Use execFile (not exec) to prevent shell injection
    // msw-auto-mock is invoked as a subprocess with arguments as array
    await execFileAsync('npx', ['msw-auto-mock', specPath, ...args], {
      cwd: process.cwd(),
    })
  } catch {
    // msw-auto-mock might not be installed, generate basic handlers instead
    if (options.verbose) {
      console.log(chalk.dim('[Generator] msw-auto-mock not available, using basic handler generator'))
    }
    await generateBasicHandlers(spec, options)
  }

  // Post-process generated files
  await postProcess(outputDir, specHash)

  // Collect handler information
  const handlers = spec.endpoints.map(endpoint => ({
    path: endpoint.path,
    method: endpoint.method,
    operationId: endpoint.operationId,
  }))

  return {
    outputDir,
    handlers,
    specHash,
  }
}

/**
 * Build command-line arguments for msw-auto-mock based on options.
 * Maps GeneratorOptions to CLI flags for the subprocess.
 * @param options - Generator configuration options
 * @returns Array of CLI arguments for msw-auto-mock
 */
function buildArgs(options: GeneratorOptions): string[] {
  const args: string[] = []

  args.push('-o', options.outputDir)

  if (options.typescript !== false) {
    args.push('--typescript')
  }

  if (options.baseUrl) {
    args.push('--base-url', options.baseUrl)
  }

  if (options.includes?.length) {
    args.push('-t', options.includes.join(','))
  }

  if (options.excludes?.length) {
    args.push('-e', options.excludes.join(','))
  }

  if (options.maxArrayLength) {
    args.push('--max-array-length', String(options.maxArrayLength))
  }

  if (options.static) {
    args.push('--static')
  }

  return args
}

/**
 * Generate basic MSW handlers when msw-auto-mock is not available
 */
async function generateBasicHandlers(
  spec: Awaited<ReturnType<typeof parseSpec>>,
  options: GeneratorOptions
): Promise<void> {
  const { outputDir, typescript } = options
  const ext = typescript !== false ? 'ts' : 'js'

  const handlers: string[] = []

  for (const endpoint of spec.endpoints) {
    // Generate handler with comment showing operation ID if available
    const comment = endpoint.operationId ? ` // ${endpoint.operationId}` : ''

    handlers.push(`
  http.${endpoint.method}('${spec.baseUrl ?? ''}${endpoint.path}', () => {${comment}
    // TODO: Generate realistic response data
    return HttpResponse.json(${JSON.stringify({ message: 'Generated by Pactwork' })})
  }),`)
  }

  const handlersContent = `// Generated by Pactwork - DO NOT EDIT
// Spec hash: [pending]
// Generated at: ${new Date().toISOString()}

import { http, HttpResponse } from 'msw'

export const handlers = [${handlers.join('\n')}
]
`

  await fs.writeFile(path.join(outputDir, `handlers.${ext}`), handlersContent)

  // Generate browser setup
  const browserContent = `// Generated by Pactwork
import { setupWorker } from 'msw/browser'
import { handlers } from './handlers'

export const worker = setupWorker(...handlers)
`

  await fs.writeFile(path.join(outputDir, `browser.${ext}`), browserContent)

  // Generate node setup
  const nodeContent = `// Generated by Pactwork
import { setupServer } from 'msw/node'
import { handlers } from './handlers'

export const server = setupServer(...handlers)
`

  await fs.writeFile(path.join(outputDir, `node.${ext}`), nodeContent)
}

/**
 * Post-process generated files to add Pactwork metadata
 */
async function postProcess(outputDir: string, specHash: string): Promise<void> {
  const handlersPath = path.join(outputDir, 'handlers.ts')

  if (await fs.pathExists(handlersPath)) {
    let content = await fs.readFile(handlersPath, 'utf-8')

    // Add or update Pactwork header
    if (!content.includes('Generated by Pactwork')) {
      content = `// Generated by Pactwork
// Spec hash: ${specHash}
// Generated at: ${new Date().toISOString()}

${content}`
      await fs.writeFile(handlersPath, content)
    } else {
      // Update spec hash
      content = content.replace(/Spec hash: \w+/, `Spec hash: ${specHash}`)
      await fs.writeFile(handlersPath, content)
    }
  }
}
